### ISSUE TITLE
A few questions about design decisions when configuring OkHttp

### ISSUE THREAD

**Issue by jean-t86** [azygous13/NimbleAndroidChallenge#10]
I am curious about the following when configuring the OkHttp client:

1. Why is Gson using `setLenient()`?

2. Why were the default timeouts changed, i.e. for `connectTimeout`, `readTimeout`, and `writeTimeout`?

**Comment by azygous13** [comment]
Sorry about this, It's my mistake. I reuse this module from my old project. I will remove it. Thank you.

**Comment by jean-t86** [comment]
Curious still, why was it set up that way in your old project?

**Comment by azygous13** [comment]
I use setLenient to accept malformed JSON from the API. I don't  know why the backend team provide me a API like this.
